# **Limpieza y análisis exploratorio del DataFrame 1: actividad de clientes**

## **1. Carga de datos**

### **1.1 Librerias**

In [ ]:
# Importación de librerías necesarias para análisis y visualización de datos
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### **1.2 Base de datos de la historica de todos los estados**

In [16]:
# Base de datos de todos los estados
datos_estados = "./data/all-states-history.csv"

# Carga del dataset
df_states = pd.read_csv(datos_estados)
df_states.head()

,date,state,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
0,2021-03-07,AK,305.0,NaN,0,NaN,1293.0,1293.0,33.0,0,...,1731628.0,0,NaN,NaN,NaN,NaN,NaN,0,1731628.0,0
1,2021-03-07,AL,10148.0,7963.0,-1,2185.0,45976.0,45976.0,494.0,0,...,2323788.0,2347,NaN,NaN,119757.0,NaN,2323788.0,2347,NaN,0
2,2021-03-07,AR,5319.0,4308.0,22,1011.0,14926.0,14926.0,335.0,11,...,2736442.0,3380,NaN,NaN,NaN,481311.0,NaN,0,2736442.0,3380
3,2021-03-07,AS,0.0,NaN,0,NaN,NaN,NaN,NaN,0,...,2140.0,0,NaN,NaN,NaN,NaN,NaN,0,2140.0,0
4,2021-03-07,AZ,16328.0,14403.0,5,1925.0,57907.0,57907.0,963.0,44,...,7908105.0,45110,580569.0,NaN,444089.0,NaN,3842945.0,14856,7908105.0,45110

In [33]:
df_states.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20780 entries, 0 to 20779
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   date                              20780 non-null  object
 1   state                             20780 non-null  object
 2   death                             19930 non-null  float64
 3   deathConfirmed                    9422 non-null   float64
 4   deathIncrease                     20780 non-null  int64
 5   deathProbable                     7593 non-null   float64
 6   hospitalized                      12382 non-null  float64
 7   hospitalizedCumulative            12382 non-null  float64
 8   hospitalizedCurrently             17339 non-null  float64
 9   hospitalizedIncrease              20780 non-null  int64
 10  inIcuCumulative                   3789 non-null   float64
 11  inIcuCurrently                    11636 non-null  float64
 12  negative                          13290 non-null  float64
 13  negativeIncrease                  20780 non-null  int64
 14  negativeTestsAntibody             1458 non-null   float64
 15  negativeTestsPeopleAntibody       972 non-null    float64
 16  negativeTestsViral                5024 non-null   float64
 17  onVentilatorCumulative            1290 non-null   float64
 18  onVentilatorCurrently             9126 non-null   float64
 19  positive                          20592 non-null  float64
 20  positiveCasesViral                14246 non-null  float64
 21  positiveIncrease                  20780 non-null  int64
 22  positiveScore                     20780 non-null  int64
 23  positiveTestsAntibody             3346 non-null   float64
 24  positiveTestsAntigen              2233 non-null   float64
 25  positiveTestsPeopleAntibody       1094 non-null   float64
 26  positiveTestsPeopleAntigen        633 non-null    float64
 27  positiveTestsViral                8958 non-null   float64
 28  recovered                         12003 non-null  float64
 29  totalTestEncountersViral          5231 non-null   float64
 30  totalTestEncountersViralIncrease  20780 non-null  int64
 31  totalTestResults                  20614 non-null  float64
 32  totalTestResultsIncrease          20780 non-null  int64
 33  totalTestsAntibody                4789 non-null   float64
 34  totalTestsAntigen                 3421 non-null   float64
 35  totalTestsPeopleAntibody          2200 non-null   float64
 36  totalTestsPeopleAntigen           999 non-null    float64
 37  totalTestsPeopleViral             9197 non-null   float64
 38  totalTestsPeopleViralIncrease     20780 non-null  int64
 39  totalTestsViral                   14516 non-null  float64
 40  totalTestsViralIncrease           20780 non-null  int64
dtypes: float64(30), int64(9), object(2)
memory usage: 6.5+ MB

In [32]:
print(df_states.describe())

              death  deathConfirmed  deathIncrease  deathProbable  \
count  19930.000000     9422.000000   20780.000000    7593.000000
mean    3682.216859     3770.182764      24.790712     417.291321
std     6281.366321     4157.640633      60.162742     537.625982
min        0.000000        0.000000    -201.000000       0.000000
25%      161.250000      607.000000       0.000000      79.000000
50%     1108.000000     2409.500000       6.000000     216.000000
75%     4387.500000     5462.000000      24.000000     460.000000
max    54124.000000    21177.000000    2559.000000    2594.000000

       hospitalized  hospitalizedCumulative  hospitalizedCurrently  \
count  12382.000000            12382.000000           17339.000000
mean    9262.762478             9262.762478            1190.576965
std    12620.544081            12620.544081            2060.041207
min        1.000000                1.000000               0.000000
25%      985.250000              985.250000             166.500000
50%     4472.000000             4472.000000             531.000000
75%    12248.500000            12248.500000            1279.000000
max    82237.000000            82237.000000           22851.000000

       hospitalizedIncrease  inIcuCumulative  inIcuCurrently  ...  \
count          20780.000000      3789.000000    11636.000000  ...
mean              37.360780      1934.191607      359.621176  ...
std              208.237151      1953.329983      594.831150  ...
min           -12257.000000         6.000000        0.000000  ...
25%                0.000000       501.000000       60.000000  ...
50%                0.000000      1295.000000      172.000000  ...
75%               36.000000      2451.000000      380.000000  ...
max            16373.000000      9263.000000     5225.000000  ...

       totalTestResults  totalTestResultsIncrease  totalTestsAntibody  \
count      2.061400e+04              20780.000000        4.789000e+03
mean       2.186936e+06              17508.388210        1.634028e+05
std        4.436508e+06              33586.022461        2.016978e+05
min        0.000000e+00            -130545.000000        0.000000e+00
25%        1.040498e+05               1205.750000        1.896500e+04
50%        6.552670e+05               6125.000000        8.465200e+04
75%        2.264766e+06              19086.500000        2.300110e+05
max        4.964601e+07             473076.000000        1.054711e+06

       totalTestsAntigen  totalTestsPeopleAntibody  totalTestsPeopleAntigen  \
count       3.421000e+03               2200.000000               999.000000
mean        3.089196e+05             165431.783182            168188.246246
std         4.232854e+05             178181.836898            143748.073365
min         1.000000e+00                  1.000000                 3.000000
25%         2.004700e+04              54912.750000             37675.500000
50%         1.233840e+05             103967.500000            144130.000000
75%         4.327270e+05             183103.000000            255251.000000
max         2.664340e+06             995580.000000            580372.000000

       totalTestsPeopleViral  totalTestsPeopleViralIncrease  totalTestsViral  \
count           9.197000e+03                   2.078000e+04     1.451600e+04
mean            9.650105e+05                   2.739554e+03     2.304555e+06
std             1.415215e+06                   1.621900e+04     4.445365e+06
min             0.000000e+00                  -1.043744e+06     0.000000e+00
25%             1.414700e+05                   0.000000e+00     1.324600e+05
50%             4.193720e+05                   0.000000e+00     7.316510e+05
75%             1.229298e+06                   2.478000e+03     2.496925e+06
max             1.124825e+07                   8.208170e+05     4.964601e+07

       totalTestsViralIncrease
count             2.078000e+04
mean              1.296143e+04
std               3.749509e+04
min              -1.154583e+06
25%               0.000000e+00
50%               1.896500e+03
75%               1.244100e+04
max               2.164543e+06

[8 rows x 39 columns]

### **1.3 Base de datos de los datos nacionales**

In [23]:
#Base de datos nivel nacional
datos_nacional = "./data/national-history.csv"

#Carga del dataset nivel nacional
df_national = pd.read_csv(datos_nacional)
df_national.head()

,date,death,deathIncrease,inIcuCumulative,inIcuCurrently,hospitalizedIncrease,hospitalizedCurrently,hospitalizedCumulative,negative,negativeIncrease,onVentilatorCumulative,onVentilatorCurrently,positive,positiveIncrease,states,totalTestResults,totalTestResultsIncrease
0,2021-03-07,515151.0,842,45475.0,8134.0,726,40199.0,776361.0,74582825.0,131835,4281.0,2802.0,28756489.0,41835,56,363825123,1170059
1,2021-03-06,514309.0,1680,45453.0,8409.0,503,41401.0,775635.0,74450990.0,143835,4280.0,2811.0,28714654.0,60015,56,362655064,1430992
2,2021-03-05,512629.0,2221,45373.0,8634.0,2781,42541.0,775132.0,74307155.0,271917,4275.0,2889.0,28654639.0,68787,56,361224072,1744417
3,2021-03-04,510408.0,1743,45293.0,8970.0,1530,44172.0,772351.0,74035238.0,177957,4267.0,2973.0,28585852.0,65487,56,359479655,1590984
4,2021-03-03,508665.0,2449,45214.0,9359.0,2172,45462.0,770821.0,73857281.0,267001,4260.0,3094.0,28520365.0,66836,56,357888671,1406795

In [34]:
df_national.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      420 non-null    object
 1   death                     392 non-null    float64
 2   deathIncrease             420 non-null    int64
 3   inIcuCumulative           348 non-null    float64
 4   inIcuCurrently            347 non-null    float64
 5   hospitalizedIncrease      420 non-null    int64
 6   hospitalizedCurrently     356 non-null    float64
 7   hospitalizedCumulative    369 non-null    float64
 8   negative                  372 non-null    float64
 9   negativeIncrease          420 non-null    int64
 10  onVentilatorCumulative    341 non-null    float64
 11  onVentilatorCurrently     348 non-null    float64
 12  positive                  419 non-null    float64
 13  positiveIncrease          420 non-null    int64
 14  states                    420 non-null    int64
 15  totalTestResults          420 non-null    int64
 16  totalTestResultsIncrease  420 non-null    int64
dtypes: float64(9), int64(7), object(1)
memory usage: 55.9+ KB

In [35]:
print(df_national.describe())

               death  deathIncrease  inIcuCumulative  inIcuCurrently  \
count     392.000000     420.000000       348.000000      347.000000
mean   187210.668367    1226.550000     21059.344828    12059.227666
std    142331.657380    1070.129644     13572.638376     5668.415483
min         0.000000       0.000000        74.000000     1299.000000
25%     86911.750000     439.750000      9900.250000     7495.500000
50%    169118.500000    1016.000000     18797.500000    10114.000000
75%    258912.250000    1642.500000     32998.500000    15596.500000
max    515151.000000    5427.000000     45475.000000    23912.000000

       hospitalizedIncrease  hospitalizedCurrently  hospitalizedCumulative  \
count            420.000000             356.000000              369.000000
mean            1848.478571           57987.117978           310817.140921
std             1708.460481           31898.555998           235557.870159
min            -2858.000000             325.000000                4.000000
25%              765.750000           35100.500000           123250.000000
50%             1490.000000           48811.000000           280138.000000
75%             2467.000000           70519.250000           481309.000000
max            17155.000000          132474.000000           776361.000000

           negative  negativeIncrease  onVentilatorCumulative  \
count  3.720000e+02        420.000000              341.000000
mean   3.030351e+07     177578.154762             2173.932551
std    2.407815e+07     121544.473208             1327.372196
min    2.000000e+00    -658774.000000               32.000000
25%    6.753778e+06      79236.750000              951.000000
50%    2.757246e+07     206620.000000             2107.000000
75%    5.084301e+07     260621.000000             3430.000000
max    7.458282e+07     480256.000000             4281.000000

       onVentilatorCurrently      positive  positiveIncrease      states  \
count             348.000000  4.190000e+02        420.000000  420.000000
mean             3975.298851  8.116687e+06      68467.830952   49.476190
std              2191.080602  8.967432e+06      68682.221496   16.896764
min               167.000000  0.000000e+00          0.000000    1.000000
25%              2168.500000  1.004386e+06      22462.500000   56.000000
50%              3186.500000  5.044337e+06      44664.500000   56.000000
75%              5828.500000  1.234137e+07      89684.250000   56.000000
max              8004.000000  2.875649e+07     295121.000000   56.000000

       totalTestResults  totalTestResultsIncrease
count      4.200000e+02              4.200000e+02
mean       1.073369e+08              8.662503e+05
std        1.129172e+08              6.579460e+05
min        0.000000e+00              0.000000e+00
25%        5.888598e+06              2.388558e+05
50%        6.839699e+07              8.223685e+05
75%        1.854937e+08              1.401706e+06
max        3.638251e+08              2.309884e+06

## **2. Empezamos la limpieza de las bases de datos**

### **2.1 Duplicados**

#### **2.1.1 Duplicados estados**

In [ ]:
# Cuenta el total de filas que están idénticas y repetidas en todo el dataset.
print(df_states.duplicated().sum())

# Muestra cuáles son esas filas duplicadas para revisar visualmente el error antes de borrarlas.
print(df_states[df_states.duplicated(keep=False)])

0
Empty DataFrame
Columns: [date, state, death, deathConfirmed, deathIncrease, deathProbable, hospitalized, hospitalizedCumulative, hospitalizedCurrently, hospitalizedIncrease, inIcuCumulative, inIcuCurrently, negative, negativeIncrease, negativeTestsAntibody, negativeTestsPeopleAntibody, negativeTestsViral, onVentilatorCumulative, onVentilatorCurrently, positive, positiveCasesViral, positiveIncrease, positiveScore, positiveTestsAntibody, positiveTestsAntigen, positiveTestsPeopleAntibody, positiveTestsPeopleAntigen, positiveTestsViral, recovered, totalTestEncountersViral, totalTestEncountersViralIncrease, totalTestResults, totalTestResultsIncrease, totalTestsAntibody, totalTestsAntigen, totalTestsPeopleAntibody, totalTestsPeopleAntigen, totalTestsPeopleViral, totalTestsPeopleViralIncrease, totalTestsViral, totalTestsViralIncrease]
Index: []

[0 rows x 41 columns]

In [21]:
# Elimina las filas duplicadas manteniendo solo la primera aparición para no adulterar el análisis estadístico.
df_states = df_states.drop_duplicates()

#### **2.1.2 Duplicados nacional**

In [27]:
# Cuenta el total de filas que están idénticas y repetidas en todo el dataset.
print(df_national.duplicated().sum())

# Muestra cuáles son esas filas duplicadas para revisar visualmente el error antes de borrarlas.
print(df_national[df_national.duplicated(keep=False)])

0
Empty DataFrame
Columns: [date, death, deathIncrease, inIcuCumulative, inIcuCurrently, hospitalizedIncrease, hospitalizedCurrently, hospitalizedCumulative, negative, negativeIncrease, onVentilatorCumulative, onVentilatorCurrently, positive, positiveIncrease, states, totalTestResults, totalTestResultsIncrease]
Index: []

In [28]:
# Elimina las filas duplicadas manteniendo solo la primera aparición para no adulterar el análisis estadístico.
df_national = df_national.drop_duplicates()

### **2.2 Valores nulos en nuestra base de datos**

#### **2.2.1 Valores nulos estados**

In [18]:
# Muestra cuántos valores nulos hay en cada columna para identificar qué datos están incompletos.
print(df_states.isnull().sum())

# Calcula el porcentaje de nulos por columna para evaluar si vale la pena conservar o eliminar una variable.
print((df_states.isnull().sum() / len(df_states)) * 100)

date                                    0
state                                   0
death                                 850
deathConfirmed                      11358
deathIncrease                           0
deathProbable                       13187
hospitalized                         8398
hospitalizedCumulative               8398
hospitalizedCurrently                3441
hospitalizedIncrease                    0
inIcuCumulative                     16991
inIcuCurrently                       9144
negative                             7490
negativeIncrease                        0
negativeTestsAntibody               19322
negativeTestsPeopleAntibody         19808
negativeTestsViral                  15756
onVentilatorCumulative              19490
onVentilatorCurrently               11654
positive                              188
positiveCasesViral                   6534
positiveIncrease                        0
positiveScore                           0
positiveTestsAntibody               17434
positiveTestsAntigen                18547
positiveTestsPeopleAntibody         19686
positiveTestsPeopleAntigen          20147
positiveTestsViral                  11822
recovered                            8777
totalTestEncountersViral            15549
totalTestEncountersViralIncrease        0
totalTestResults                      166
totalTestResultsIncrease                0
totalTestsAntibody                  15991
totalTestsAntigen                   17359
totalTestsPeopleAntibody            18580
totalTestsPeopleAntigen             19781
totalTestsPeopleViral               11583
totalTestsPeopleViralIncrease           0
totalTestsViral                      6264
totalTestsViralIncrease                 0
dtype: int64
date                                 0.000000
state                                0.000000
death                                4.090472
deathConfirmed                      54.658325
deathIncrease                        0.000000
deathProbable                       63.460058
hospitalized                        40.413859
hospitalizedCumulative              40.413859
hospitalizedCurrently               16.559192
hospitalizedIncrease                 0.000000
inIcuCumulative                     81.766121
inIcuCurrently                      44.003850
negative                            36.044273
negativeIncrease                     0.000000
negativeTestsAntibody               92.983638
negativeTestsPeopleAntibody         95.322425
negativeTestsViral                  75.822907
onVentilatorCumulative              93.792108
onVentilatorCurrently               56.082772
positive                             0.904716
positiveCasesViral                  31.443696
positiveIncrease                     0.000000
positiveScore                        0.000000
positiveTestsAntibody               83.897979
positiveTestsAntigen                89.254090
positiveTestsPeopleAntibody         94.735322
positiveTestsPeopleAntigen          96.953802
positiveTestsViral                  56.891242
recovered                           42.237729
totalTestEncountersViral            74.826756
totalTestEncountersViralIncrease     0.000000
totalTestResults                     0.798845
totalTestResultsIncrease             0.000000
totalTestsAntibody                  76.953802
totalTestsAntigen                   83.537055
totalTestsPeopleAntibody            89.412897
totalTestsPeopleAntigen             95.192493
totalTestsPeopleViral               55.741097
totalTestsPeopleViralIncrease        0.000000
totalTestsViral                     30.144370
totalTestsViralIncrease              0.000000
dtype: float64

#### **2.2.2 Valores Nacional**

In [29]:
# Muestra cuántos valores nulos hay en cada columna para identificar qué datos están incompletos.
print(df_national.isnull().sum())

# Calcula el porcentaje de nulos por columna para evaluar si vale la pena conservar o eliminar una variable.
print((df_national.isnull().sum() / len(df_national)) * 100)

date                         0
death                       28
deathIncrease                0
inIcuCumulative             72
inIcuCurrently              73
hospitalizedIncrease         0
hospitalizedCurrently       64
hospitalizedCumulative      51
negative                    48
negativeIncrease             0
onVentilatorCumulative      79
onVentilatorCurrently       72
positive                     1
positiveIncrease             0
states                       0
totalTestResults             0
totalTestResultsIncrease     0
dtype: int64
date                         0.000000
death                        6.666667
deathIncrease                0.000000
inIcuCumulative             17.142857
inIcuCurrently              17.380952
hospitalizedIncrease         0.000000
hospitalizedCurrently       15.238095
hospitalizedCumulative      12.142857
negative                    11.428571
negativeIncrease             0.000000
onVentilatorCumulative      18.809524
onVentilatorCurrently       17.142857
positive                     0.238095
positiveIncrease             0.000000
states                       0.000000
totalTestResults             0.000000
totalTestResultsIncrease     0.000000
dtype: float64